### PR TITLE
Gamesforfree 002

### PR DESCRIPTION
**Pull request by hojongyu2**
Registered my models with the Django admin site. Created connection with Django and React. Watch mode is added as well

### CODE REVIEW

**Comment by nfrankeln** [comment]
Could you put your schema and wireframe in a readme.

**Comment by hojongyu2** [comment]
Readme updated

**Review by nfrankeln — APPROVED** [review]
Rating_choices could be named score if tis just a number if its an actual unique list of choices you might need a choices table
if profile_pic is a url type text would be better suited to handle long url links

**Comment by hojongyu2** [comment]
Thanks for the input. I will keep it as it is for now since there are only three rating choices. I will refractor as I build my project.

**Pull request merged**
